-- Seed data is generated deterministically by backend/seed.py so the same
-- dataset works with PostgreSQL and the local SQLite development database.
--
-- From the backend directory run:
--     python seed.py
--
-- Result: 1 demo user, 25 doctors, 10 products, and 100 interactions.
